---
title: "<<date>>: Epidemic Mitigation Time Forecast (Covid-19)"
date: <<date>>
slug: predict-<<date>>
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE, collapse = TRUE, out.width = "100%")
Sys.setlocale('LC_CTYPE', 'Chinese')
```

```{r}
require(ncovr)
ncovChina <- get_ncov('china') 
ncovChina <- ncovChina[ncovChina[, "日期"] < as.Date('<<date>>'), ]
```

## Time trends and model predictions of confirmed cases across the country


```{r}

if(as.Date('<<date>>') < as.Date('2020-02-13')) {
  predict_date(province = "中国",  ncov = ncovChina, PredDate = as.Date('<<date>>'))
} else{

#nCov prediction, new model
#Yi Zou
#Last modified: "2020-02-29 10:53:45 CST"
PredDate <- format(as.Date('<<date>>') ,"%m-%d") #*****Set the date you want to predict

#Libarary and data
library(mgcv)
DtChina_all <- ncovChina[ncovChina[, "日期"] < as.Date('<<date>>'), ]

DtChina <- DtChina_all[,c(1,2,4,6,7)]
names (DtChina) <- c("Date","Confirmed","Suspected","Death","Cured")

#Data since 2020-1-17
DatJan17 <- data.frame(Date = seq(from=as.Date("2020-01-17",format="%Y-%m-%d"),to=DtChina$Date[1]-1,by = "day"),
                       Confirmed = c(58,136,198),
                       Death = c(1,1,4),
                       Suspected = c(NA,NA,NA),
                       Cured = c(NA,NA,NA))

#Dataframe
Dat <- rbind(DatJan17,DtChina)
Dat$Day <- 1:nrow(Dat)
Dat$NewCured <- with(Dat,Cured-c(0,Cured[-nrow(Dat)]))
Dat$NewCured <- replace(Dat$NewCured,Dat$NewCured<0,NA)
Dat$NewDeath <- with(Dat,Death-c(0,Death[-nrow(Dat)]))
Dat$Total <- Dat$Confirmed + Dat$Suspected 

#Fit the model with 3-parameter logistic regression
Dat$Ymod <- Dat$Total #Model varialbe, may change to "Total"

#Other data  
Dat$Sick <- with(Dat, Ymod - Death - Cured)
Dat$RateD <- with(Dat,NewDeath / (Sick))
Dat$RateC <- with(Dat,NewCured / Sick)
Dat$New <- with(Dat,Ymod-c(0,Ymod[-nrow(Dat)]))


Mrd <- mean(Dat$RateD[-(1:15)],na.rm=T)#The daily death:current sick ratio is about 0.00287 for later cases,#The daily death: total confirmed ratio is 0.0026 for later cases


#Model for Ymod (confirmed)
# md <- nls(Ymod~SSlogis(Day, Asym, xmid, scal),data= Dat )
md <- nls(Ymod~SSlogis(Day, Asym, xmid, scal),data= Dat[-(24:26),] )
Coe <- summary(md)$coefficients
a <- Coe[1,1]
xmax <-  2*Coe[2,1]

#Fit the model for NewCured (Daily cured)
# mdNc <- nls(NewCured~SSlogis(Day, Asym, xmid, scal),data= Dat )
mdNc <- nls(NewCured~SSlogis(Day, Asym, xmid, scal),data= Dat[-(24:26),] )


#Fit the model for Daily death rate
mdDc <-gam(RateD~s(Day),data= Dat[-(1:5),]) #Perfect model fitting
# with(Dat[-(1:5),],plot(x=Day,y=RateD,ylim=c(0,0.02),xlim=c(1,100)))
# Pred <- seq(0, 3*xmax, length = 100)
# lines(Pred, predict(mdDc, list(Day = Pred)),col="red")


#New data frame
ND <- as.numeric(Sys.Date()-as.Date("2020-01-17",format="%Y-%m-%d")+15)
Pred=1:ND
newdat <- data.frame(Pred)
newdat$Date <- format(seq(Dat$Date[1], by = "day", length.out = length(Pred) ),"%m-%d")
newdat$Judge <- ifelse(newdat$Date ==PredDate,"Tmr",ifelse(newdat$Date < PredDate,"Obs","Pre"))

newdat$pYmod <- predict(md,  list(Day = Pred ))
newdat$pDaily <- with(newdat,pYmod -c(0,pYmod [-nrow(newdat)]))


#-----------Another way to calculate current sick 2020-02-26
     #Fit the model for Daily death rate
     mdDc <-gam(RateD~s(Day),data= Dat[-(1:5),]) #Perfect model fitting
     
     #fit the model for deaily cured rate
     fitdc <- gam(RateC~s(Day),data= Dat[-c(1:8,24:26),])
     
     Fun <- 1+Mrd+predict(fitdc,list(Day = Pred))#Fixed daily death rate
     #Fun <- 1+predict(mdDc, list(Day = Pred))+predict(fitdc,list(Day = Pred))#changing death rate
     
     pSick <- vector()
     pSick[1] <-  newdat$ pYmod[1] / Fun[1]
     for (i in 2:length(newdat$pYmod))
    {
    pSick[i] <- (newdat$pDaily[i]+pSick[i-1])/Fun[i]
     }
     newdat$pSick <- pSick
     newdat$pDailyCured <- newdat$pSick*predict(fitdc, list(Day = Pred))
     newdat$pTotalCured <-  cumsum(newdat$pDailyCured)
     #newdat$pDailyDeath <- newdat$pSick*predict(mdDc, list(Day = Pred)) #For changing daily death rate
     newdat$pDailyDeath <- newdat$pSick*Mrd #Fixed daily death rate
     newdat$pTotalDeath <- cumsum(newdat$pDailyDeath)
     newdat$pRateC <- with (newdat, pDailyCured/pSick)
     newdat$pRateD <- with (newdat, pDailyDeath/pSick)
     newdat$pRateTC <- with (newdat, pTotalCured/pYmod)
     newdat$pRateTD <- with (newdat, pTotalDeath/pYmod)
#------------------------------------------------------------

#Plot the data
par(mgp = c(2.5, 0.6, 0))
with(Dat,plot(y=Ymod,x=Day,xlim=c(0,max(newdat[,"pSick">0]$Pred)),ylim=c(0,1.2*a),ylab="Number of cases",xlab="",bty='n',xaxt = "n",col="red",pch=1,yaxt = "n"));title("China")
with(Dat,points(y=Cured,x=Day,col="green",pch=1))
with(Dat,points(y=Sick,x=Day,col="orange",pch=1))
    with(Dat,points(y=Death,x=Day,col="grey",pch=1))
with(Dat,points(y=NewCured,x=Day,col="purple",pch=1))
with(Dat,points(y=New,x=Day,col="blue",pch=1))
axis(2, cex.axis = 0.6,las=1)

#Plot the prediction line
#Before PreDate

newdat_l <- subset(newdat,Judge=="Obs")
with(newdat_l,lines(x=Pred,y=pYmod,col="red",lty=1))
with(newdat_l,lines(x=Pred,y=pDaily,col="blue",lty=1))
with(newdat_l,lines(x=Pred,y=pSick,col="orange",lty=1))
with(newdat_l,lines(x=Pred,y=pTotalCured,col="green",lty=1))
with(newdat_l,lines(x=Pred,y=pDailyCured,col="purple",lty=1))
   with(newdat_l,lines(x=Pred,y=pTotalDeath,col="grey",lty=1))

#After PreDate
newdat_l <- subset(newdat,Judge=="Pre")
with(newdat_l,lines(x=Pred,y=pYmod,col="red",lty=2))
with(newdat_l,lines(x=Pred,y=pDaily,col="blue",lty=2))
with(newdat_l,lines(x=Pred,y=pSick,col="orange",lty=2))
with(newdat_l,lines(x=Pred,y=pTotalCured,col="green",lty=2))
with(newdat_l,lines(x=Pred,y=pDailyCured,col="purple",lty=2))
   with(newdat_l,lines(x=Pred,y=pTotalDeath,col="grey",lty=2))

#Predation point
newdat_l <- subset(newdat,Judge=="Tmr")
with(newdat_l,points(x=Pred,y=pYmod,col="red",pch=19))
with(newdat_l,points(x=Pred,y=pDaily,col="blue",pch=19))
  with(newdat_l,points(x=Pred,y=pTotalDeath,col="grey",pch=19))
with(newdat_l,points(x=Pred,y=pSick,col="orange",pch=19))
with(newdat_l,points(x=Pred,y=pTotalCured,col="green",pch=19))
with(newdat_l,points(x=Pred,y=pDailyCured,col="purple",pch=19))

#Axis
# axis(1, at=newdat$Pred, labels=newdat$Date,cex.axis = 0.5,las=2)
axis(1, at=newdat$Pred[seq(1, nrow(newdat), by = 2)] , labels=newdat$Date[seq(1, nrow(newdat), by = 2)],cex.axis = 0.5,las=2)

#Legend
# legend("topleft", legend=c("Confirmed & suspected ","Daily increase","Total recover","Daily recover","Current active","Total death"), col=c("red", "blue","green","purple","orange","grey"), pch = 1, cex=0.6, bty='n')
legend("topleft", legend=c("Confirmed & Suspected","Current Active (Confirmed & Suspected)","Daily Increase","Total Recover","Daily Recover","Total Death"), col=c("red", "orange","blue","green","purple","grey"), pch = 1, cex=0.6, bty='n')

legend("topright", legend=c("Observed","Predicted"), col="black", pch = c(1,19), cex=0.6, bty='n')
legend("top", legend=c("Model fit","Predicted"), col=c("black","black"), lty = 1:2, cex=0.6, bty='n')
box()

text(0.5*xmax,0.1*a,paste("laiyindata"),col=rgb(red = 0, green = 0, blue =0, alpha = 0.05),srt = 30,cex=4,adj=0)}
```



```{r}
pre <- predict_date(province = "中国",  ncov = ncovChina, ifplot = FALSE)
 
 

```


```{r, results='asis'}
if(as.Date('<<date>>') < as.Date('2020-02-13')){
  cat("Our model shows that the national epidemic situation will ease on", pre$enddate, "(the number of confirmed cases will not increase significantly).  \\n\\n On", 
      as.character(pre$tomorrow),  "there will be", format(round(pre$tomorrowNew), scientific = FALSE), "new confirmed cases and in total", format(round(pre$tomorrowcount), scientific = FALSE), "confirmed cases."
  )
} else {
  cat('Due to the adding of clinical diagnosis to confirm cases, since February 13, our model will use the “confirmed + suspected” cases instead of the original “confirmed” cases as our variables. Data from February 09, 10 and 11 were removed from the model because cases were underreported and then included all at once on February 12. ')
}
```


## National Epidemic Time Series

<small>

```{r}
ncovChina <- get_ncov('china', if_en = TRUE) 
ncovChina <- ncovChina[rev(order(ncovChina[, 1])), ]
ncovChina[, 1] <- format(ncovChina[, 1], '%m-%d')
# knitr::kable(ncovChina[, !names(ncovChina) %in% c("Updated", "Remarks")], format = "html", row.names = FALSE)

flextable::flextable(ncovChina[, !names(ncovChina) %in% c("Updated", "Remarks")])
```

</small>


```{r}
ncov <- get_ncov()
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[ncov$area$date < as.Date('<<date>>'), ]
df_predict <- t(sapply(unique(ncov$area$provinceShortName[ncov$area$countryName == '中国']), function(x) predict_date(province = x, ncov = ncov, ifplot = FALSE)))


df_predict <- as.data.frame(df_predict)
df_predict$area <- unlist(df_predict$area)
df_predict <- df_predict[order(-as.numeric(df_predict$tomorrowNew)), ]

dic_city <-  readr::read_csv(system.file('china_city_list.csv', package = 'ncovr'))
df_predict$area_en <- unlist(dic_city[match(df_predict$area, dic_city$Province), 'Province_EN'])

tomorrow <- df_predict$tomorrow[1]
```

```{r, results='asis'}
cat("## <<date>> Epidemic forecast by province")
```

```{r}
y <- df_predict[!is.na(df_predict$enddate), c(6, 1, 2, 5, 4)]

names(y) <- c("[Area]", '[Area_cn]', "[Epidemic Mitigation Time]", paste0("[", tomorrow[[1]], " Prdctd daily incrs conf.]"), paste0("[", tomorrow[[1]], " Prdctd conf. in total]"))
flextable::flextable(y)
```

```{r, results='asis'}
Prov <- c("湖北", unique(ncov$area$provinceShortName[ncov$area$countryName == '中国' & !ncov$area$provinceShortName %in% c('湖北', '待明确地区')]))

for(x in Prov) {
  cat(unlist(dic_city[match(x, dic_city$Province), 'Province_EN']), ":  \n", sep = '')
  predict_date(province = x, ncov = ncov, ifplot = TRUE, ifchinese = FALSE, predDate = as.Date('<<date>>'))
  cat("  \n")
}
```

This model prediction is provided by Dr. Yi Zou.
