---
title: 2019-nCoV 疫情地图(<<method-zh>>级)<<date>>
date: <<date>>
slug: <<method>>-map-<<date>>
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE)
Sys.setlocale('LC_CTYPE', 'Chinese')
```

更新时间：`r format(Sys.time(), tz = "Asia/Shanghai")` (北京时间)

<iframe seamless src="https://pzhaonet.github.io/ncov/leaflet/leafmap-<<method>>-<<date>>.html" width="100%" height="500"></iframe>

[点击这里全屏显示。](https://pzhaonet.github.io/ncov/leaflet/leafmap-<<method>>-<<date>>.html)


```{r}
require(ncovr)
require(leafletCN)
ncov <- get_ncov()
ncov$area$date <- as.character(as.Date(ncovr:::conv_time(ncov$area$updateTime)))
ncov$area <- ncov$area[!duplicated(paste(ncov$area$provinceName, ncov$area$date)), ]
x <- ncov$area[ncov$area$date == "<<date>>", c(2, 3, 5, 6)]

method <- "<<method>>"

if(method == 'city'){
  x_city <- dplyr::bind_rows(ncov$area$cities[ncov$area$date == "<<date>>"])
  names(x)[1] <- "cityName"
  if(nrow(x_city) > 0) x <- rbind(x_city[, c(1, 2, 4, 5)], x)
  cities <- leafletCN::regionNames(mapName = "city")
  x <- x[x$cityName %in% cities, ]
}

prefix <- switch(method, "province" = "省", "city" = "市")
x <- x[order(-x$confirmedCount), ]
x$rank <- 1:nrow(x)
x <- x[, c(5,1:4)]
```

```{r, results='asis'}
cat("## <<date>> 疫情数据表(", prefix, ")")
```

```{r}
knitr::kable(x, format = "html", row.names = FALSE, col.names = c("排序", "名称", "确诊", "治愈", "死亡"))
```
