# baseurl = "https://pzhaonet.github.io/ncov/"
baseurl = "https://ncov2020.org/"
# baseurl = "file:///D:/github/ncov/docs/"
# languageCode = "en-us"
languageCode = "zh-cn"
theme = "hugo-lithium"
googleAnalytics = "UA-157876946-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"
DefaultContentLanguage = "zh"


[languages]
  [languages.en]
    contentDir = "content/en"
    title = "Covid-19: Epidemic Reports"
  [languages.zh]
    contentDir = "content/zh"
    title = "Covid-19：新型冠状病毒疫情报告"
    
  [[languages.en.menu.main]]
    name = "Homepage"
    url = "/en/"
    weight = 10
  [[languages.en.menu.main]]
    name = "Overview"
    url = "/en/intro/"
    weight = 20
  [[languages.en.menu.main]]
    name = "News"
    url = "/news/"
    weight = 40
  [[languages.en.menu.main]]
    name = "Data"
    url = "/en/data/"
    weight = 60
  [[languages.en.menu.main]]
    name = "Market"
    url = "/en/tags/shared/"
    weight = 65
  [[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 70
  [[languages.en.menu.main]]
    name = "中文"
    url = "/zh/"
    weight = 80

  [[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[languages.zh.menu.main]]
    name = "概览"
    url = "/intro/"
    weight = 20
  [[languages.zh.menu.main]]
    name = "简讯"
    url = "/news/"
    weight = 40
  [[languages.zh.menu.main]]
    name = "辟谣"
    url = "/rumors/"
    weight = 50
  [[languages.zh.menu.main]]
    name = "数据下载"
    url = "/data/"
    weight = 60
  [[languages.zh.menu.main]]
    name = "防疫物资"
    url = "/tags/shared/"
    weight = 65
  [[languages.zh.menu.main]]
    name = "关于本站"
    url = "/about/"
    weight = 70
  [[languages.zh.menu.main]]
    name = "English"
    url = "/en/"
    weight = 80
    
  [languages.en.permalinks]
    post = "/en/:slug/"
  [languages.zh.permalinks]
    post = "/zh/:slug/"



[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "pzhao.org"

