---
title: 疫情缓和时间预测(2020-02-01)
date: 2020-02-01
slug: predict-2020-02-01
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE)
Sys.setlocale('LC_CTYPE', 'Chinese')
```

```{r}
require(ncovr)
ncovChina <- get_ncov('china') 
ncovChina <- ncovChina[ncovChina$`日期` < as.Date('2020-02-01'), ]
```

## 全国确诊病例时间趋势图和模型预测

```{r}
predict_date(province = "中国",  ncov = ncovChina,type="confirmed")
pre <- predict_date(province = "中国",  ncov = ncovChina,type="confirmed", ifplot = FALSE)
```


我们的模型显示，全国总体疫情将于 `r pre$enddate` 缓解（确诊病例不再明显增长）。

2020-`r pre$tomorrow` 确诊病例将新增`r format(round(pre$tomorrowNew), scientific = FALSE)`例，累计确诊病例将达到 `r format(round(pre$tomorrowcount), scientific = FALSE)` 例。

## 全国疫情时间序列

```{r}
knitr::kable(ncovChina[, 1:9], format = "html", row.names = FALSE)
```


```{r}
ncov <- get_ncov()
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[ncov$area$date < as.Date('2020-02-01'), ]
df_predict <- t(sapply(unique(ncov$area$provinceShortName), function(x) predict_date(province = x, ncov = ncov, ifplot = FALSE)))
df_predict <- as.data.frame(df_predict)
df_predict <- df_predict[order(-as.numeric(df_predict$tomorrowNew)), ]
tomorrow <- substr(as.character(as.Date(paste0('2002-', df_predict$tomorrow[1]))-1), 6,  10)
```

```{r, results='asis'}
cat("## 2020-02-01 各地区疫情预测表")
```

```{r}
knitr::kable(df_predict[, c(1, 2, 5, 4)], format = "html", row.names = FALSE, col.names = c("地区", "疫情缓解日期", paste0(tomorrow, "新增确诊人数预测"), paste0(tomorrow, "累计确诊人数预测")))
```

```{r, results='asis'}
for(x in unique(ncov$area$provinceShortName)) {
  cat(x, ":  \n")
  predict_date(province = x, ncov = ncov, ifplot = TRUE, ifchinese = TRUE)
  cat("  \n")
}
```
