---
title: 疫情预测2020-02-04
date: 2020-02-04
slug: predict-2020-02-04
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE)
```

```{r}
require(ncovr)
Sys.setlocale('LC_CTYPE', 'Chinese')
```


## 全国确诊病例时间趋势图和模型预测

```{r}
ncov <- get_ncov('china')
Confirmed <- c(58, 136, 198, ncov[, '确诊'])
Suspected <- c(NA,  NA,  NA, ncov[, '疑似'])
Death <- c(1, 1, 4, ncov[, '死亡'])
Dat <- data.frame(Confirmed, Death, Suspected)
# 设置一列为时间
Dat$Date <- seq(as.Date("2020-01-17",format="%Y-%m-%d"),
                by = "day", 
                length.out = nrow(Dat))
# 以1月17日作为第一天，是x变量
Dat$Day <- 1:nrow(Dat)
# 选择模型的y，我们先以确诊病例作为y
Dat$Ymod <- Dat$Confirmed
#模型需要设置初始值，但是我们也可以采用自动初始值用SSlogis()函数
md <- nls(Ymod ~ SSlogis(Day, Asym, xmid, scal), data = Dat)
Coe <- summary(md)$coefficients
a <- Coe[1, 1]# 第一个参数Coe[1,1]是模型渐近线
xmax <-  2 * Coe[2, 1] #第二个参数Coe[2,1]是模型x中值
with(Dat,
     plot(y = Ymod, x = Day,
          xlim = c(0, 1.8 * xmax),
          ylim = c(0, 1.2 * a),
          ylab = "Number of cases",
          xlab = "",
          bty = 'n',
          xaxt = "n"
     )
) #用xaxt = "n"先隐藏x轴

#模型的预测值和预测线
Pred <- seq(0, 1.2 * xmax, length = 100)
lines(Pred, predict(md, list(Day = Pred)), col = "red")

#画上x轴
Length <- round(2.2 * nrow(Dat), 0)#需要预测到第几天，这里采用2.2倍的我们的数据时间
Dseq <- format(seq(Dat$Date[1], by = "day", length.out = Length), "%m-%d") #设置新的x轴标签
axis(1, at = 1:Length, labels = Dseq,
    cex.axis = 0.6,las = 2)

#做一个简单的图例，当然也可以用legend做图例
points(2, 0.8 * a)
text(3, 0.8 * a, "Confirmed", cex = 0.8, adj = 0)
segments(1.5, 0.7 * a, 2.5, 0.7 * a, col = "red")
text(3, 0.7 * a, "Model fit", cex = 0.8, adj = 0)

#画上两条参考线
segments(0, a, xmax, a, lty = "dotted")
segments(xmax, 0, xmax, a, lty = "dotted")
Input = nrow(Dat) + 1

```


我们的模型显示，全国总体疫情将于 `r Dseq [round(xmax,0)]` 结束。

明天（2020-02-04）的累计确诊病例预计是 `r format(round(Coe[1, 1] / (1 + exp((Coe[2, 1] - Input) / Coe[3, 1]))), scientific=FALSE)` 例。


```{r}
ncov <- get_ncov()
df_predict <- t(sapply(unique(ncov$area$provinceShortName), function(x) predict_date(province = x, ncov = ncov, ifplot = FALSE)))
df_predict <- as.data.frame(df_predict)
df_predict <- df_predict[order(-as.numeric(df_predict$tomorrowcount)), ]
tomorrow <- df_predict$tomorrow[1]
```

```{r, results='asis'}
cat("## 2020-02-04 各地区疫情预测表")
```

```{r}
knitr::kable(df_predict[, c(1, 2, 4)], format = "html", row.names = FALSE, col.names = c("地区", "结束时间", paste0("今日(", tomorrow, ")确诊人数预测")))
```

```{r, results='asis'}
fig <- sapply(unique(ncov$area$provinceShortName), function(x) {
  predict_date(province = x, ncov = ncov)$fig
  cat(x, '\\n' )
  }
  )
```

