---
title: "2020-02-06: 市级疫情地图 (2019-nCoV)"
date: 2020-02-06
slug: city-map-2020-02-06
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE)
Sys.setlocale('LC_CTYPE', 'Chinese')
```

更新时间：`r format(Sys.time(), tz = "Asia/Shanghai")` (北京时间)

<iframe seamless src="https://pzhaonet.github.io/ncov/leaflet/leafmap-city-2020-02-06.html" width="100%" height="500"></iframe>

图中灰色区域表示缺少该区域城市的相关数据。

[点击这里全屏显示。](https://pzhaonet.github.io/ncov/leaflet/leafmap-city-2020-02-06.html)


```{r}
require(ncovr)
require(leafletCN)
ncov <- get_ncov()
ncov$area <- ncov$area[ncov$area$country == '中国' & ncov$area$provinceName != '待明确地区' , ]
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[rev(order(ncov$area$date)), ]
ncov$area <- ncov$area[ncov$area$date <= as.Date("2020-02-06"), ]
ncov$area <- ncov$area[!duplicated(ncov$area$provinceName), ]
x <- ncov$area[, c('provinceShortName', 'confirmedCount', 'curedCount', 'deadCount')]
names(x)[1] <- 'provinceName'

method <- "city"

if(method == 'city'){
  x <- x[x$provinceName %in% c("北京", "上海", "重庆", "天津"), ]
  names(x)[1] <- "cityName"
  x_city <- get_ncov('tidy')$area
  x_city$date <- x_city$updateTime
  x_city <- x_city[rev(order(x_city$date)), ]
  x_city <- x_city[as.Date(x_city$date) <= as.Date("2020-02-06"), ]
  x_city <- x_city[!duplicated(x_city$cityName), ]
  if(nrow(x_city) > 0) x <- rbind(x_city[, c('cityName', 'confirmedCount', 'curedCount', 'deadCount')], x)
  cities <- leafletCN::regionNames(mapName = "city")
  x <- x[x$cityName %in% cities, ]
}

prefix <- switch(method, "province" = "省", "city" = "市")
x <- x[order(-x$confirmedCount), ]
x$rank <- 1:nrow(x)
x <- x[, c(5,1:4)]
```

```{r, results='asis'}
cat("## 2020-02-06 疫情数据表(", prefix, ")")
```

```{r}
# knitr::kable(x, format = "html", row.names = FALSE, col.names = c("排序", "名称", "确诊", "治愈", "死亡"))
names(x) <- c("排序", "名称", "确诊", "治愈", "死亡")
x[, "名称"] <- unlist(x[, "名称"])
flextable::flextable(x) #, col_keys = )
```
