---
title: "2020-02-08: 疫情缓和时间预测 (Covid-19)"
date: 2020-02-08
slug: predict-2020-02-08
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE, collapse = TRUE, out.width = "100%")
Sys.setlocale('LC_CTYPE', 'Chinese')
```

```{r}
require(ncovr)
require(ggplot2)

#ZouYi Last modified "2020-02-10 23:05:42 CST"
#' Predict
#'
#' @param province province short name
#' @param ncov ncov data
#' @param ifplot logic.
#'
#' @return a figure.
#' @export
#'
#' @examples
#' Sys.setlocale('LC_CTYPE', 'Chinese')
#' ncov <- get_ncov()#Get the data
#' ncovChina <-get_ncov('china')
#' predict_date(province = "jiangsuinchinese",  ncov = ncov)
#' predict_date(province = "meiguoinchinese",  ncov = ncov)
#' predict_date(province = "zhongguoinchinese",  ncov = ncovChina)
predict_date <- function(province, ncov = c(ncov,ncovChina), ifplot = TRUE, addtitle = NA, ifchinese = FALSE, fontfamily = NA,PredDate=Sys.Date()){
    dic <- readr::read_csv(system.file('dic.csv', package = 'ncovr'))
    #Dataset for a specific area
    if (province!=dic$zh[1])
    {
        Area <- ncov$area
        Area$updateTime <- ncovr:::conv_time(Area$updateTime)#Correct the time
        Area$Date <- format(Area$updateTime,"%m-%d")
        Region_all <- c("湖北以外",unique(Area$provinceShortName))
        Region_name <- Region_all[match(province, Region_all)]#Match regional name
        if (Region_name=="湖北以外"){Region <- subset(Area,provinceShortName!="湖北")}else
        {Region <- subset(Area,provinceShortName==Region_name)}
        RegionDat <- aggregate(confirmedCount~Date,data=Region,max)
        RegionDat$Date <- as.Date(RegionDat$Date,"%m-%d")
        RegionDat <- RegionDat[RegionDat$Date<Sys.Date(),]
    }
    
    if (province==dic$zh[1])
    {
        RegionDat <- data.frame(confirmedCount=c(58, 136, 198, ncovChina[,2]))
        RegionDat$Date <- seq(as.Date("2020-01-17",format="%Y-%m-%d"),by = "day", length.out = nrow(RegionDat))
        
    }
    
    #No data availalbe for specific date
    RegionDat$Day <- as.numeric(RegionDat$Date-RegionDat$Date[1])+1
    RegionDat$New <- with(RegionDat,confirmedCount-c(0,confirmedCount[-nrow(RegionDat)]))
    Length <- as.numeric(PredDate-as.Date(RegionDat$Date[1],"%m-%d")+20)#x axis from today to 20 days later
    Dseq <- format(seq(RegionDat$Date[1], by = "day", length.out = Length ),"%m-%d")
    
    END <- NA
    Predict <- NA
    NewIncrease <- NA
    NewIncrease2 <- NA
    a <- NA
    xmax <- NA
    r.sq <- NA
    
    # #Model logistic regression
    an.error.occured <- 0
    tryCatch({
        md <- nls(confirmedCount~SSlogis(Day, Asym, xmid, scal),data= RegionDat)
        Coe <- summary(md)$coefficients
        a <- Coe[1,1]
        xmax <-  2*Coe[2,1]
        
        #End date
        END = Dseq [round(xmax,0)]
        #Predict
        Input=nrow(RegionDat)+1
        Predict <- round(a/(1+exp((Coe[2,1]-Input)/Coe[3,1])),0)
        #Model fit
        
        X1 <- RegionDat[complete.cases(RegionDat$confirmedCount),"confirmedCount"]
        Y1 <- predict(md,X1)
        r.sq <- max(cor(X1,Y1),0)^2
        #The daily increase case
        Lth <- as.numeric(as.Date(END,"%m-%d")-as.Date(Dseq[1],"%m-%d"))
        newdat <-  data.frame(Date=as.Date(Dseq[1:Lth],"%m-%d"),Pred=1:Lth)
        newdat <- within(newdat, ypred <- predict(md,  list(Day = Pred )))
        newdat$Prednew <- with(newdat,ypred-c(0,ypred[-nrow(newdat)]))
        newdat$Judge <- ifelse(newdat$Date ==PredDate,"Tmr",ifelse(newdat$Date < PredDate,"Obs","Pre"))
    if (PredDate+1>as.Date(END,"%m-%d")){NewIncrease <- 0}else
    {NewIncrease <- round( newdat[which(newdat$Judge=="Tmr"),"Prednew"],0)}
        if (PredDate+2>as.Date(END,"%m-%d")){NewIncrease2 <- 0}else
        {NewIncrease2 <- round( newdat[which(newdat$Judge=="Tmr")+1,"Prednew"],0)}
        
    }, error = function(e) {an.error.occured <<- 1})
    
    if(ifplot){
      p <-  ggplot(RegionDat,aes(y=confirmedCount,x=Date))+
          annotate(geom="text", x=median(as.Date(Dseq,"%m-%d")), y=max(RegionDat$confirmedCount,na.rm=T),  label='laiyindata', color='grey90', angle=45, fontface='bold', size=15,alpha=0.4)+
          geom_point(aes(col="总数"),shape=1,col="red")+
          ylim(0,2*max(RegionDat$confirmedCount,na.rm=T))+
          xlab("")+
          ylab("确诊案例")+
          ggtitle(province) #Title of the plot, in Chinese
 #         geom_point(aes(y=New,x=Date,col="日增"),shape=1)+
  #        scale_colour_manual(name = '', values =c('blue','red'))
        if(an.error.occured == 0 & r.sq>0.90)
        {
            newdatmg <- merge(newdat,RegionDat,by="Date",all=T)
            Ldft <- which(newdatmg$Judge=="Tmr")+1
            p <- ggplot(subset(newdatmg,Judge!="Tmr"),aes(y=confirmedCount,x=Date))+
                annotate(geom="text", x=median(as.Date(Dseq,"%m-%d")), y=0.5*a,  label='laiyindata', color='grey90', angle=45, fontface='bold', size=15,alpha=0.4)+
                ylim(0,1.2*a)+
                xlab("")+
                ylab("确诊案例")+
                ggtitle(province)+ #Title of the plot, in Chinese
                geom_point(aes(col="总数"),shape=1,size=2.5)+
                geom_point(aes(y=New,x=Date,col="日增"),shape=1,size=2.5)+
                scale_colour_manual(name = '', values =c('red','blue'))+
                geom_line(aes(y=ypred,x=Date,linetype=Judge),col="red")+
                geom_line(aes(y=Prednew,x=Date,linetype=Judge),col="blue")+
                scale_linetype_manual(name = '',values=c(1,2),labels=c("模型拟合","模型预测"))
                if(NewIncrease>0)
                {p <- p+with(subset(newdatmg,Judge=="Tmr"),geom_point(aes(shape="明日值"),y=ypred,x=Date,col="red",size=3))+
                with(subset(newdatmg,Judge=="Tmr"),geom_point(y=Prednew,x=Date,col="red",size=2))+labs(shape="",col="")
                }
        }
      p <- p+theme_bw(base_family = "STKaiti")+
          theme(axis.text.x = element_text(angle = 90, hjust = 1),
                legend.key = element_rect(colour = NA, fill = NA),
                legend.title=element_blank(),
                legend.background = element_rect(fill=NA, size=0.5, colour =NA),
                legend.position=c(0.75,0.31),
                legend.justification = c(0,0))+
          scale_x_date(date_breaks = "1 day", date_labels = "%m-%d",limits=c(as.Date("1-17","%m-%d"),PredDate+20),expand=c(0,0.5))
      print(p)
#      return(p)
      } else {
        list(area = province,
             enddate = END,
             tomorrow = PredDate,
             tomorrowcount = Predict,
             tomorrowNew=NewIncrease,
             dayafterNew=NewIncrease2)
    }
}
ncovChina <- get_ncov('china') 
ncovChina <- ncovChina[ncovChina[, "日期"] <= as.Date('2020-02-08'), ]
```

## 全国确诊病例时间趋势图和模型预测

```{r}
predict_date(province = "中国",  ncov = ncovChina)
pre <- predict_date(province = "中国",  ncov = ncovChina, ifplot = FALSE, PredDate = as.Date(  '2020-02-08'))
```


我们的模型显示，全国总体疫情将于 `r pre$enddate` 缓解（确诊病例不再明显增长）。

`r pre$tomorrow` 确诊病例将新增`r format(round(pre$tomorrowNew), scientific = FALSE)`例，累计确诊病例将达到 `r format(round(pre$tomorrowcount), scientific = FALSE)` 例。

## 全国疫情时间序列

<small>

```{r}
ncovChina <- ncovChina[rev(order(ncovChina[, 1])), ]
x <- ncovChina[, 1:9]
flextable::flextable(x)

# knitr::kable(ncovChina[, 1:9], format = "html", row.names = FALSE)
```

</small>


```{r}
ncov <- get_ncov()
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[ncov$area$date < as.Date('2020-02-08'), ]
df_predict <- t(sapply(unique(ncov$area$provinceShortName[ncov$area$country == '中国']), function(x) predict_date(province = x, ncov = ncov, ifplot = FALSE, PredDate = as.Date(  '2020-02-08'))))

df_predict <- as.data.frame(df_predict)
df_predict <- df_predict[order(-as.numeric(df_predict$tomorrowNew)), ]
tomorrow <- df_predict$tomorrow[1]
```

```{r, results='asis'}
cat("## 2020-02-08 各地区疫情预测表")
```

```{r}
y <- df_predict[!is.na(df_predict$enddate), c(1, 2, 5, 4)]

names(y) <- c("地区", "疫情缓解日期", paste(tomorrow[[1]], "新增确诊人数预测"), paste(tomorrow[[1]], "累计确诊人数预测"))
flextable::flextable(y)

```

```{r, results='asis'}
Prov <- c("湖北", "湖北以外", unique(ncov$area$provinceShortName[ncov$area$country == '中国' & !ncov$area$provinceShortName %in% c('湖北', '待明确地区')]))

for(x in Prov) {
  cat(x, ":  \n")
    predict_date(province = x,  ncov = ncov, PredDate = as.Date(  '2020-02-08'))
  cat("  \n")
}
```
