---
title: "2020-02-10: Epidemic Map for cities (Covid-19)"
date: 2020-02-10
slug: city-map-2020-02-10
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE)
Sys.setlocale('LC_CTYPE', 'Chinese')
```

Updated: `r format(Sys.time(), tz = "Asia/Shanghai")` (UTC+08:00)

<iframe seamless src="https://pzhaonet.github.io/ncov/leaflet/leafmap-city-2020-02-10.html" width="100%" height="500"></iframe>

Confirmed cases. The gray area in the figure indicates the lack of relevant data of the cities in this area.

[Click here for full screen display.](https://pzhaonet.github.io/ncov/leaflet/leafmap-city-2020-02-10.html)


```{r}
require(ncovr)
require(leafletCN)
ncov <- get_ncov()
ncov$area <- ncov$area[ncov$area$country == '中国' & ncov$area$provinceName != '待明确地区' , ]
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[rev(order(ncov$area$date)), ]
ncov$area <- ncov$area[ncov$area$date <= as.Date("2020-02-10"), ]
ncov$area <- ncov$area[!duplicated(ncov$area$provinceName), ]
x <- ncov$area[, c('provinceShortName', 'confirmedCount', 'curedCount', 'deadCount', 'province_en')]
names(x)[1] <- 'provinceName'

method <- "city"

if(method == 'city'){
  x <- x[x$provinceName %in% c("北京", "上海", "重庆", "天津"), ]
  names(x)[1] <- "cityName"
  names(x)[5] <- "city_en"
  x$city_en <- unlist(x$city_en)
  x_city <- get_ncov('tidy')$area
  x_city$date <- x_city$updateTime
  x_city <- x_city[rev(order(x_city$date)), ]
  x_city <- x_city[as.Date(x_city$date) <= as.Date("2020-02-10"), ]
  x_city <- x_city[!duplicated(x_city$cityName), ]
  if(nrow(x_city) > 0) x <- rbind(x_city[, c('cityName', 'confirmedCount', 'curedCount', 'deadCount', 'city_en')], x)
  cities <- leafletCN::regionNames(mapName = "city")
  x <- x[x$cityName %in% cities, ]
  require(pinyin)
  mydic <- pydic('toneless', dic = 'pinyin2')
  x$city_en[is.na(x$city_en)] <- ncovr:::conv_firstletter(py(x$cityName[is.na(x$city_en)], dic = mydic, sep =''))
}

prefix <- switch(method, "province" = "Provinces", "city" = "Cities")
x <- x[order(-x$confirmedCount), ]
x$rank <- 1:nrow(x)
x <- x[, c(6,5, 1:4)]
```

```{r, results='asis'}
cat("## 2020-02-10 Epidemic Data Sheet (", prefix, ")")
```

```{r}
# knitr::kable(x, format = "html", row.names = FALSE, col.names = c("Rank", "Area", "Area_cn", "Confirmed", "Cured", "Dead"))
names(x) <- c("Rank", "Area", "Area_cn", "Confirmed", "Cured", "Dead")
x$Area <- unlist(x$Area)
flextable::flextable(x)
```
