---
title: "<<date>>: 疫情缓和时间预测 (Covid-19)"
date: <<date>>
slug: predict-<<date>>
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE, error = FALSE, collapse = TRUE, out.width = "100%")
Sys.setlocale('LC_CTYPE', 'Chinese')
```

```{r}
require(ncovr)
require(ggplot2)

#ZouYi Last modified "2020-02-10 23:05:42 CST"
#' Predict
#'
#' @param province province short name
#' @param ncov ncov data
#' @param ifplot logic.
#'
#' @return a figure.
#' @export
#'
#' @examples
#' Sys.setlocale('LC_CTYPE', 'Chinese')
#' ncov <- get_ncov()#Get the data
#' ncovChina <-get_ncov('china')
#' predict_date(province = "jiangsuinchinese",  ncov = ncov)
#' predict_date(province = "meiguoinchinese",  ncov = ncov)
#' predict_date(province = "zhongguoinchinese",  ncov = ncovChina)
predict_date <- function(province, ncov = c(ncov,ncovChina), ifplot = TRUE, addtitle = NA, ifchinese = FALSE, fontfamily = NA,PredDate=Sys.Date()){
    dic <- readr::read_csv(system.file('dic.csv', package = 'ncovr'))
    #Dataset for a specific area
    if (province!=dic$zh[1])
    {
        Area <- ncov$area
        Area$updateTime <- ncovr:::conv_time(Area$updateTime)#Correct the time
        Area$Date <- format(Area$updateTime,"%m-%d")
        Region_all <- c("湖北以外",unique(Area$provinceShortName))
        Region_name <- Region_all[match(province, Region_all)]#Match regional name
          if(Region_name=="湖北以外"){
            Region_sub <- subset(Area,provinceShortName!="湖北"&countryEnglishName=="China")
            RegionDat_max <- aggregate(confirmedCount~Date+provinceShortName,data=Region_sub,max) 
            RegionDat <- aggregate(confirmedCount~Date,data=RegionDat_max,sum)
            }else
        {Region <- subset(Area,provinceShortName==Region_name)
        RegionDat <- aggregate(confirmedCount~Date,data=Region,max)}
        RegionDat$Date <- as.Date(RegionDat$Date,"%m-%d")
        RegionDat <- RegionDat[RegionDat$Date<Sys.Date(),]
    }
    
    if (province==dic$zh[1])
    {
        RegionDat <- data.frame(confirmedCount=c(58, 136, 198, ncovChina[,2]))
        RegionDat$Date <- seq(as.Date("2020-01-17",format="%Y-%m-%d"),by = "day", length.out = nrow(RegionDat))
        
    }
    
    #No data availalbe for specific date
    RegionDat$Day <- as.numeric(RegionDat$Date-RegionDat$Date[1])+1
    RegionDat$New <- with(RegionDat,confirmedCount-c(0,confirmedCount[-nrow(RegionDat)]))
    Length <- as.numeric(PredDate-as.Date(RegionDat$Date[1],"%m-%d")+20)#x axis from today to 20 days later
    Dseq <- format(seq(RegionDat$Date[1], by = "day", length.out = Length ),"%m-%d")
    
    END <- NA
    Predict <- NA
    NewIncrease <- NA
    NewIncrease2 <- NA
    a <- NA
    xmax <- NA
    r.sq <- NA
    
    # #Model logistic regression
    an.error.occured <- 0
    tryCatch({
        md <- nls(confirmedCount~SSlogis(Day, Asym, xmid, scal),data= RegionDat)
        Coe <- summary(md)$coefficients
        a <- Coe[1,1]
        xmax <-  2*Coe[2,1]
        
        #End date
        END = Dseq [round(xmax,0)]
        #Predict
        Input=nrow(RegionDat)+1
        Predict <- round(a/(1+exp((Coe[2,1]-Input)/Coe[3,1])),0)
        #Model fit
        
        X1 <- RegionDat[complete.cases(RegionDat$confirmedCount),"confirmedCount"]
        Y1 <- predict(md,X1)
        r.sq <- max(cor(X1,Y1),0)^2
        #The daily increase case
        Lth <- as.numeric(as.Date(END,"%m-%d")-as.Date(Dseq[1],"%m-%d"))
        newdat <-  data.frame(Date=as.Date(Dseq[1:Lth],"%m-%d"),Pred=1:Lth)
        newdat <- within(newdat, ypred <- predict(md,  list(Day = Pred )))
        newdat$Prednew <- with(newdat,ypred-c(0,ypred[-nrow(newdat)]))
        newdat$Judge <- ifelse(newdat$Date ==PredDate,"Tmr",ifelse(newdat$Date < PredDate,"Obs","Pre"))
    if (PredDate+1>as.Date(END,"%m-%d")){NewIncrease <- 0}else
    {NewIncrease <- round( newdat[which(newdat$Judge=="Tmr"),"Prednew"],0)}
        if (PredDate+2>as.Date(END,"%m-%d")){NewIncrease2 <- 0}else
        {NewIncrease2 <- round( newdat[which(newdat$Judge=="Tmr")+1,"Prednew"],0)}
        
    }, error = function(e) {an.error.occured <<- 1})
    
    if(ifplot){
      p <-  ggplot(RegionDat,aes(y=confirmedCount,x=Date))+
          annotate(geom="text", x=median(as.Date(Dseq,"%m-%d")), y=max(RegionDat$confirmedCount,na.rm=T),  label='laiyindata', color='grey90', angle=45, fontface='bold', size=15,alpha=0.4)+
          geom_point(aes(col="总数"),shape=1,col="red")+
          ylim(0,2*max(RegionDat$confirmedCount,na.rm=T))+
          xlab("")+
          ylab("确诊案例")+
          ggtitle(province) #Title of the plot, in Chinese
 #         geom_point(aes(y=New,x=Date,col="日增"),shape=1)+
  #        scale_colour_manual(name = '', values =c('blue','red'))
        if(an.error.occured == 0 & r.sq>0.90)
        {
            newdatmg <- merge(newdat,RegionDat,by="Date",all=T)
            Ldft <- which(newdatmg$Judge=="Tmr")+1
            p <- ggplot(subset(newdatmg,Judge!="Tmr"),aes(y=confirmedCount,x=Date))+
                annotate(geom="text", x=median(as.Date(Dseq,"%m-%d")), y=0.5*a,  label='laiyindata', color='grey90', angle=45, fontface='bold', size=15,alpha=0.4)+
                ylim(0,1.2*a)+
                xlab("")+
                ylab("确诊案例")+
                ggtitle(province)+ #Title of the plot, in Chinese
                geom_point(aes(col="总数"),shape=1,size=2.5)+
                geom_point(aes(y=New,x=Date,col="日增"),shape=1,size=2.5)+
                scale_colour_manual(name = '', values =c('red','blue'))+
                geom_line(aes(y=ypred,x=Date,linetype=Judge),col="red")+
                geom_line(aes(y=Prednew,x=Date,linetype=Judge),col="blue")+
                scale_linetype_manual(name = '',values=c(1,2),labels=c("模型拟合","模型预测"))
                if(NewIncrease>0)
                {p <- p+with(subset(newdatmg,Judge=="Tmr"),geom_point(aes(shape="明日值"),y=ypred,x=Date,col="red",size=3))+
                with(subset(newdatmg,Judge=="Tmr"),geom_point(y=Prednew,x=Date,col="red",size=2))+labs(shape="",col="")
                }
        }
      p <- p+theme_bw(base_family = "STKaiti")+
          theme(axis.text.x = element_text(angle = 90, hjust = 1),
                legend.key = element_rect(colour = NA, fill = NA),
                legend.title=element_blank(),
                legend.background = element_rect(fill=NA, size=0.5, colour =NA),
                legend.position=c(0.75,0.31),
                legend.justification = c(0,0))+
          scale_x_date(date_breaks = "1 day", date_labels = "%m-%d",limits=c(as.Date("1-17","%m-%d"),PredDate+20),expand=c(0,0.5))
      print(p)
#      return(p)
      } else {
        list(area = province,
             enddate = END,
             tomorrow = PredDate,
             tomorrowcount = Predict,
             tomorrowNew=NewIncrease,
             dayafterNew=NewIncrease2)
    }
}
ncovChina <- get_ncov('china') 
ncovChina <- ncovChina[ncovChina[, "日期"] < as.Date('<<date>>'), ]
```

## 全国确诊病例时间趋势图和模型预测

```{r}

if(as.Date('<<date>>') < as.Date('2020-02-13')) {
  predict_date(province = "中国",  ncov = ncovChina, PredDate = as.Date('<<date>>'))
} else{

#nCov prediction, new model
#Yi Zou
#Last modified: "2020-02-29 10:53:45 CST"
PredDate <- format(as.Date('<<date>>') ,"%m-%d") #*****Set the date you want to predict

#Libarary and data
library(mgcv)
DtChina_all <- ncovChina[ncovChina[, "日期"] < as.Date('<<date>>'), ]

DtChina <- DtChina_all[,c(1,2,4,6,7)]
names (DtChina) <- c("Date","Confirmed","Suspected","Death","Cured")

#Data since 2020-1-17
DatJan17 <- data.frame(Date = seq(from=as.Date("2020-01-17",format="%Y-%m-%d"),to=DtChina$Date[1]-1,by = "day"),
                       Confirmed = c(58,136,198),
                       Death = c(1,1,4),
                       Suspected = c(NA,NA,NA),
                       Cured = c(NA,NA,NA))

#Dataframe
Dat <- rbind(DatJan17,DtChina)
Dat$Day <- 1:nrow(Dat)
Dat$NewCured <- with(Dat,Cured-c(0,Cured[-nrow(Dat)]))
Dat$NewCured <- replace(Dat$NewCured,Dat$NewCured<0,NA)
Dat$NewDeath <- with(Dat,Death-c(0,Death[-nrow(Dat)]))
Dat$Total <- Dat$Confirmed + Dat$Suspected 

#Fit the model with 3-parameter logistic regression
Dat$Ymod <- Dat$Total #Model varialbe, may change to "Total"

#Other data  
Dat$Sick <- with(Dat, Ymod - Death - Cured)
Dat$RateD <- with(Dat,NewDeath / (Sick))
Dat$RateC <- with(Dat,NewCured / Sick)
Dat$New <- with(Dat,Ymod-c(0,Ymod[-nrow(Dat)]))


Mrd <- mean(Dat$RateD[-(1:15)],na.rm=T)#The daily death:current sick ratio is about 0.00287 for later cases,#The daily death: total confirmed ratio is 0.0026 for later cases


#Model for Ymod (confirmed)
# md <- nls(Ymod~SSlogis(Day, Asym, xmid, scal),data= Dat )
md <- nls(Ymod~SSlogis(Day, Asym, xmid, scal),data= Dat[-(24:26),] )
Coe <- summary(md)$coefficients
a <- Coe[1,1]
xmax <-  2*Coe[2,1]

#Fit the model for NewCured (Daily cured)
# mdNc <- nls(NewCured~SSlogis(Day, Asym, xmid, scal),data= Dat )
mdNc <- nls(NewCured~SSlogis(Day, Asym, xmid, scal),data= Dat[-(24:26),] )


#Fit the model for Daily death rate
mdDc <-gam(RateD~s(Day),data= Dat[-(1:5),]) #Perfect model fitting
# with(Dat[-(1:5),],plot(x=Day,y=RateD,ylim=c(0,0.02),xlim=c(1,100)))
# Pred <- seq(0, 3*xmax, length = 100)
# lines(Pred, predict(mdDc, list(Day = Pred)),col="red")


#New data frame
ND <- as.numeric(Sys.Date()-as.Date("2020-01-17",format="%Y-%m-%d")+15)
Pred=1:ND
newdat <- data.frame(Pred)
newdat$Date <- format(seq(Dat$Date[1], by = "day", length.out = length(Pred) ),"%m-%d")
newdat$Judge <- ifelse(newdat$Date ==PredDate,"Tmr",ifelse(newdat$Date < PredDate,"Obs","Pre"))

newdat$pYmod <- predict(md,  list(Day = Pred ))
newdat$pDaily <- with(newdat,pYmod -c(0,pYmod [-nrow(newdat)]))


#-----------Another way to calculate current sick 2020-02-26
     #Fit the model for Daily death rate
     mdDc <-gam(RateD~s(Day),data= Dat[-(1:5),]) #Perfect model fitting
     
     #fit the model for deaily cured rate
     fitdc <- gam(RateC~s(Day),data= Dat[-c(1:8,24:26),])
     
     Fun <- 1+Mrd+predict(fitdc,list(Day = Pred))#Fixed daily death rate
     #Fun <- 1+predict(mdDc, list(Day = Pred))+predict(fitdc,list(Day = Pred))#changing death rate
     
     pSick <- vector()
     pSick[1] <-  newdat$ pYmod[1] / Fun[1]
     for (i in 2:length(newdat$pYmod))
    {
    pSick[i] <- (newdat$pDaily[i]+pSick[i-1])/Fun[i]
     }
     newdat$pSick <- pSick
     newdat$pDailyCured <- newdat$pSick*predict(fitdc, list(Day = Pred))
     newdat$pTotalCured <-  cumsum(newdat$pDailyCured)
     #newdat$pDailyDeath <- newdat$pSick*predict(mdDc, list(Day = Pred)) #For changing daily death rate
     newdat$pDailyDeath <- newdat$pSick*Mrd #Fixed daily death rate
     newdat$pTotalDeath <- cumsum(newdat$pDailyDeath)
     newdat$pRateC <- with (newdat, pDailyCured/pSick)
     newdat$pRateD <- with (newdat, pDailyDeath/pSick)
     newdat$pRateTC <- with (newdat, pTotalCured/pYmod)
     newdat$pRateTD <- with (newdat, pTotalDeath/pYmod)
#------------------------------------------------------------



#Plot the data
par(mgp = c(2.5, 0.6, 0))
with(Dat,plot(y=Ymod,x=Day,xlim=c(0,max(newdat[,"pSick">0]$Pred)),ylim=c(0,1.2*a),ylab="Number of cases",xlab="",bty='n',xaxt = "n",col="red",pch=1,yaxt = "n"));title("China")
with(Dat,points(y=Cured,x=Day,col="green",pch=1))
with(Dat,points(y=Sick,x=Day,col="orange",pch=1))
    with(Dat,points(y=Death,x=Day,col="grey",pch=1))
with(Dat,points(y=NewCured,x=Day,col="purple",pch=1))
with(Dat,points(y=New,x=Day,col="blue",pch=1))
axis(2, cex.axis = 0.6,las=1)

#Plot the prediction line
#Before PreDate

newdat_l <- subset(newdat,Judge=="Obs")
with(newdat_l,lines(x=Pred,y=pYmod,col="red",lty=1))
with(newdat_l,lines(x=Pred,y=pDaily,col="blue",lty=1))
with(newdat_l,lines(x=Pred,y=pSick,col="orange",lty=1))
with(newdat_l,lines(x=Pred,y=pTotalCured,col="green",lty=1))
with(newdat_l,lines(x=Pred,y=pDailyCured,col="purple",lty=1))
   with(newdat_l,lines(x=Pred,y=pTotalDeath,col="grey",lty=1))

#After PreDate
newdat_l <- subset(newdat,Judge=="Pre")
with(newdat_l,lines(x=Pred,y=pYmod,col="red",lty=2))
with(newdat_l,lines(x=Pred,y=pDaily,col="blue",lty=2))
with(newdat_l,lines(x=Pred,y=pSick,col="orange",lty=2))
with(newdat_l,lines(x=Pred,y=pTotalCured,col="green",lty=2))
with(newdat_l,lines(x=Pred,y=pDailyCured,col="purple",lty=2))
   with(newdat_l,lines(x=Pred,y=pTotalDeath,col="grey",lty=2))

#Predation point
newdat_l <- subset(newdat,Judge=="Tmr")
with(newdat_l,points(x=Pred,y=pYmod,col="red",pch=19))
with(newdat_l,points(x=Pred,y=pDaily,col="blue",pch=19))
  with(newdat_l,points(x=Pred,y=pTotalDeath,col="grey",pch=19))
with(newdat_l,points(x=Pred,y=pSick,col="orange",pch=19))
with(newdat_l,points(x=Pred,y=pTotalCured,col="green",pch=19))
with(newdat_l,points(x=Pred,y=pDailyCured,col="purple",pch=19))

#Axis
# axis(1, at=newdat$Pred, labels=newdat$Date,cex.axis = 0.5,las=2)
axis(1, at=newdat$Pred[seq(1, nrow(newdat), by = 2)] , labels=newdat$Date[seq(1, nrow(newdat), by = 2)],cex.axis = 0.5,las=2)

#Legend
# legend("topleft", legend=c("Confirmed & suspected ","Daily increase","Total recover","Daily recover","Current active","Total death"), col=c("red", "blue","green","purple","orange","grey"), pch = 1, cex=0.6, bty='n')
legend("topleft", legend=c("Confirmed & Suspected","Current Active (Confirmed & Suspected)","Daily Increase","Total Recover","Daily Recover","Total Death"), col=c("red", "orange","blue","green","purple","grey"), pch = 1, cex=0.6, bty='n')

legend("topright", legend=c("Observed","Predicted"), col="black", pch = c(1,19), cex=0.6, bty='n')
legend("top", legend=c("Model fit","Predicted"), col=c("black","black"), lty = 1:2, cex=0.6, bty='n')
box()

text(0.5*xmax,0.1*a,paste("laiyindata"),col=rgb(red = 0, green = 0, blue =0, alpha = 0.05),srt = 30,cex=4,adj=0)}
```


```{r}
pre <- predict_date(province = "中国",  ncov = ncovChina, ifplot = FALSE, PredDate =  as.Date('<<date>>'))

```

```{r, results='asis'}
if(as.Date('<<date>>') < as.Date('2020-02-13')){
  cat("我们的模型显示，全国总体疫情将于", pre$enddate, "缓解（确诊病例不再明显增长）。  \\n\\n", 
      as.character(pre$tomorrow),  "确诊病例将新增", format(round(pre$tomorrowNew), scientific = FALSE), "例，累计确诊病例将达到", format(round(pre$tomorrowcount), scientific = FALSE), "例。"
  )
} else {
  cat("由于部分地区增加了临床诊断作为确诊依据，自2月13日起，我们的模型将采用“确诊+疑似”病例代替原来“确诊”病例作为我们的变量。模型中剔除了2月9日，10日与11日的数据，因为这些病例包含在2月12日。")
}
```



## 全国疫情时间序列

<small>

```{r}
ncovChina <- ncovChina[rev(order(ncovChina[, 1])), ]
ncovChina[, 1] <- format(ncovChina[, 1], '%m-%d')

flextable::flextable(ncovChina[, !names(ncovChina) %in% c("更新时间", "备注")])

# knitr::kable(ncovChina[, 1:9], format = "html", row.names = FALSE)
```

</small>


```{r}
ncov <- get_ncov()
ncov$area$date <- as.Date(ncovr:::conv_time(ncov$area$updateTime))
ncov$area <- ncov$area[ncov$area$date < as.Date('<<date>>'), ]
df_predict <- t(sapply(unique(ncov$area$provinceShortName[ncov$area$countryName == '中国']), function(x) predict_date(province = x, ncov = ncov, ifplot = FALSE, PredDate = as.Date(  '<<date>>'))))

df_predict <- as.data.frame(df_predict)
df_predict <- df_predict[order(-as.numeric(df_predict$tomorrowNew)), ]
tomorrow <- df_predict$tomorrow[1]
```

```{r, results='asis'}
cat("## <<date>> 各地区疫情预测表")
```

```{r}
y <- df_predict[!is.na(df_predict$enddate), c(1, 2, 5, 4)]

names(y) <- c("地区", "疫情缓解日期", paste(tomorrow[[1]], "新增确诊人数预测"), paste(tomorrow[[1]], "累计确诊人数预测"))
flextable::flextable(y)

```

```{r, results='asis'}
Prov <- c("湖北", "湖北以外", unique(ncov$area$provinceShortName[ncov$area$countryName == '中国' & !ncov$area$provinceShortName %in% c('湖北', '待明确地区')]))

for(x in Prov) {
  cat(x, ":  \n")
    predict_date(province = x,  ncov = ncov, PredDate = as.Date('<<date>>'))
  cat("  \n")
}
```

本模型和预测来自邹怡博士。
